from marshmallow import  Schema, fields, validate, ValidationError

class ExerciseSchema(Schema):
    id = fields.Int(dump_only = True) #generated by the db
    name = fields.Str(
        required= True,
        validate=validate.Length(min=1, error="The name cannot be blank")
    )
    category = fields.Str(
        required=True,
        validate=validate.OneOf(["strength", "cardio", "flexibility","balance"])
    )
    equipment_needed= fields.Bool(load_default = False)

class WorkoutExerciseSchema(Schema):
    id = fields.Int(dump_only=True)
    reps = fields.Int(allow_none=True, validate= validate.Range(min=1, error="Reps must be positive"))
    sets= fields.Int(allow_none=True, validate=validate.Range(min=1, error="Sets must be positive"))
    duration_seconds = fields.Int(allow_none=True, validate=validate.Range(min=1))

    exercise = fields.Nested(ExerciseSchema, dump_only=True)


class WorkoutSchema(Schema):
    id = fields.Int(dump_only=True)
    date = fields.Date(required=True)
    duration_minutes = fields.Int(
        required=True,
        validate=validate.Range(min=1, error="Duration must be a positive number measured in minutes")
    )
    notes = fields. Str(allow_none=True)

    #Shows associated WorkoutExercise when dumping
    workout_exercises = fields.List(fields.Nested(WorkoutExerciseSchema), dump_only=True)

exercise_schema = ExerciseSchema()
exercises_schema = ExerciseSchema(many=True)
workout_schema = WorkoutSchema()
workouts_schema = WorkoutSchema(many=True)
workout_exercise_schema = WorkoutExerciseSchema()

    
